import 'package:flutter/material.dart';

class Hakkimizda extends StatelessWidget {
  const Hakkimizda({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.all(10.0),
      child: SingleChildScrollView(
          child: Text("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a enim molestie, efficitur purus porta, placerat purus. Vivamus faucibus tortor a lectus hendrerit, at lacinia risus venenatis. Proin bibendum eleifend lacus, nec sagittis erat pulvinar vitae. Donec non mauris eget mi iaculis consectetur in a velit. Sed volutpat tincidunt nisi, vel dictum enim vehicula eu. Aenean sagittis risus in imperdiet aliquet. Donec sit amet velit facilisis, mollis justo a, dapibus ligula. Nullam sit amet nulla vitae justo sollicitudin pellentesque nec et mi. Vestibulum accumsan libero faucibus nunc laoreet, quis dapibus mi finibus. Donec sed convallis ligula, ut bibendum enim. Curabitur iaculis euismod consequat. Donec vel dolor ipsum. Fusce faucibus justo quis lacus viverra posuere. Praesent consequat tortor turpis, at fringilla libero accumsan condimentum. Duis blandit dapibus augue, et eleifend ligula facilisis in.\r\n\r\n" +
              "Phasellus sagittis quam eget turpis faucibus, sed gravida nunc convallis. Donec dapibus tincidunt enim in venenatis. Fusce fringilla nibh vitae mollis ullamcorper. Aenean eleifend tempor purus, sit amet luctus felis facilisis eu. Ut pretium sagittis suscipit. Nam at nulla nunc. Vivamus sed nulla vitae nisl condimentum tempor. In eget ex tempor tellus vestibulum rhoncus. Maecenas sed semper augue. Morbi tristique, ligula ac luctus molestie, neque diam volutpat turpis, non facilisis metus enim at neque. Curabitur eget elementum magna. Aliquam consectetur molestie augue, id mollis orci imperdiet nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur fermentum, magna a luctus ultricies, augue enim congue neque, vel semper orci ipsum vulputate augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\n" +
              "Donec non risus sodales, ornare urna in, dictum enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi quis mollis mi. Fusce efficitur eros id enim varius faucibus. Aliquam erat volutpat. Mauris efficitur nunc et ligula venenatis, quis semper risus commodo. Vivamus vitae mauris at mauris hendrerit pulvinar id at nisi. Proin et nulla massa. Nulla commodo libero ac lacinia ornare. Fusce elementum ligula non ex dictum iaculis. Duis pretium felis sit amet nisl luctus, sed aliquam velit pretium. Morbi felis urna, consectetur et ultrices in, bibendum eu dui. Curabitur sed vehicula orci. Cras laoreet porttitor enim eget elementum. Sed mi leo, congue non blandit vel, dapibus nec ligula.\r\n\r\n" +
              "Morbi varius lorem in dapibus gravida. Cras vitae ligula est. Nulla tincidunt tortor sem, quis bibendum tellus feugiat vel. Fusce condimentum suscipit varius. Sed luctus diam at diam egestas viverra. Integer pretium risus sed mauris vulputate feugiat. Fusce facilisis tristique ipsum quis pellentesque. Aenean vitae enim id nulla condimentum commodo quis eu arcu. Maecenas vehicula sed odio in malesuada. Sed mattis est et ante pulvinar consequat.\r\n\r\n" +
              "Quisque consectetur metus nec dui vestibulum vehicula. Ut aliquet ligula porta elit sollicitudin facilisis. Ut a ligula quis urna posuere blandit et eu purus. Fusce viverra fermentum magna ac gravida. Duis nunc massa, porta sed faucibus at, porttitor id magna. Phasellus non quam quam. Aliquam placerat ipsum ut vestibulum vehicula. Maecenas vitae urna sed urna tincidunt luctus sed eu urna. Quisque ornare lobortis faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elit vitae neque iaculis efficitur. Etiam tincidunt molestie lacus sit amet faucibus. Suspendisse malesuada ex orci, rhoncus faucibus nisi posuere et.")),
    );
  }
}
